# Generated by Django 5.2.7 on 2026-02-14 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierpayments',
            name='booking',
        ),
        migrations.AddField(
            model_name='supplierpayments',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.suppliers'),
        ),
        migrations.AlterField(
            model_name='clientpayments',
            name='receipt_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='ActivityTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price_adult', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_child', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_infant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.suppliers')),
            ],
        ),
        migrations.CreateModel(
            name='BookedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_adult', models.PositiveIntegerField(default=0)),
                ('quantity_child', models.PositiveIntegerField(default=0)),
                ('quantity_infant', models.PositiveIntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.activitytemplate')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.travelcontract')),
            ],
        ),
        migrations.AddField(
            model_name='supplierpayments',
            name='booked_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bookedactivity'),
        ),
        migrations.DeleteModel(
            name='BookedSuppliers',
        ),
    ]
