# Generated by Django 5.2.7 on 2026-02-14 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_supplierpayments_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequirements',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientpayments',
            name='payment_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AccommodationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('meal_plan', models.CharField(choices=[('breakfast', 'Breakfast'), ('half_board', 'Half Board'), ('full_board', 'Full Board')], max_length=20)),
                ('room_type', models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('twin', 'Twin Room'), ('family', 'Family Room')], max_length=20)),
                ('confirmation_number', models.CharField(blank=True, max_length=100)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.travelcontract')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.suppliers')),
            ],
        ),
        migrations.CreateModel(
            name='AirportTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField()),
                ('transfer_type', models.CharField(choices=[('arrival', 'Arrival'), ('departure', 'Departure'), ('inter_hotel', 'Inter-Hotel'), ('round_trip', 'Round Trip')], max_length=20)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.travelcontract')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.suppliers')),
            ],
        ),
        migrations.CreateModel(
            name='FlightBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_date', models.DateField()),
                ('flight_number', models.CharField(max_length=30)),
                ('departure_airport', models.CharField(max_length=120)),
                ('arrival_airport', models.CharField(max_length=120)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.travelcontract')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.suppliers')),
            ],
        ),
    ]
