# Generated by Django 5.2.7 on 2026-02-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_travelrequirements_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationbooking',
            name='status',
            field=models.CharField(choices=[('not_confirmed', 'Not Confirmed'), ('confirmed', 'Confirmed')], default='not_confirmed', max_length=20),
        ),
    ]
