# Generated by Django 5.2.7 on 2026-02-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_accommodationbooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='national_id_or_passport_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
