# Generated by Django 5.2.7 on 2026-02-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_client_national_id_or_passport_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelcontract',
            name='has_flight_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='travelcontract',
            name='has_travel_insurance',
            field=models.BooleanField(default=False),
        ),
    ]
