# Generated by Django 5.2.7 on 2026-02-15 16:09

from decimal import Decimal
from django.db import migrations, models
from django.db.models import Sum
from django.db.models.functions import Coalesce


def backfill_contract_statuses(apps, schema_editor):
    TravelContract = apps.get_model("core", "TravelContract")
    ClientPayments = apps.get_model("core", "ClientPayments")
    BookedActivity = apps.get_model("core", "BookedActivity")
    AccommodationBooking = apps.get_model("core", "AccommodationBooking")
    FlightBooking = apps.get_model("core", "FlightBooking")
    AirportTransfer = apps.get_model("core", "AirportTransfer")

    for contract in TravelContract.objects.all():
        total_paid = ClientPayments.objects.filter(contract=contract).aggregate(
            total=Coalesce(Sum("amount_paid"), Decimal("0.00"))
        )["total"]

        if total_paid < contract.total_package_price:
            next_status = "incomplete_payment"
        else:
            incomplete_supplier_payments = (
                BookedActivity.objects.filter(contract=contract, is_supplier_paid=False).exists()
                or AccommodationBooking.objects.filter(contract=contract, is_supplier_paid=False).exists()
                or FlightBooking.objects.filter(contract=contract, is_supplier_paid=False).exists()
                or AirportTransfer.objects.filter(contract=contract, is_supplier_paid=False).exists()
            )
            insurance_incomplete = contract.has_travel_insurance and not contract.is_travel_insurance_paid
            next_status = "paid_not_settled" if (incomplete_supplier_payments or insurance_incomplete) else "fully_settled"

        if contract.status != next_status:
            contract.status = next_status
            contract.save(update_fields=["status"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_supplier_field_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytemplate',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bookedactivity',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='travelcontract',
            name='status',
            field=models.CharField(choices=[('incomplete_payment', 'CLient Still Paying'), ('paid_not_settled', 'Client paid but suppliers not paid'), ('fully_settled', 'All paid')], default='incomplete_payment', max_length=30),
        ),
        migrations.RunPython(backfill_contract_statuses, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='SupplierPayments',
        ),
        migrations.DeleteModel(
            name='Suppliers',
        ),
    ]
