# Generated by Django 5.2.7 on 2026-02-15 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_activitytemplate_supplier_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airporttransfer',
            name='dropoff_location',
        ),
        migrations.RemoveField(
            model_name='airporttransfer',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='airporttransfer',
            name='pickup_location',
        ),
        migrations.RemoveField(
            model_name='airporttransfer',
            name='pickup_time',
        ),
        migrations.RemoveField(
            model_name='airporttransfer',
            name='transfer_date',
        ),
        migrations.RemoveField(
            model_name='airporttransfer',
            name='transfer_type',
        ),
    ]
