# Generated by Django 5.2.7 on 2026-02-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sync_accommodation_supplier_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationbooking',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('triple', 'Triple Room'), ('twin', 'Twin Room'), ('family', 'Family Room')], max_length=20),
        ),
    ]
