# Generated by Django 5.2.7 on 2026-02-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_accommodationbooking_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='flight_ticket_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
